### ISSUE TITLE
Laser Emission Speed

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/Asteroids#11]
Should the 'laser' be created with respect to the ship's current momentum? It is possible currently to obtain a speed where a fired laser will not escape the ship.

**Comment by MunWolf** [comment]
We probably want this though it could be a problem if the shot starts going sideways if you try to shoot perpendicular to your velocity vector.

Also this time faster shots actually hit more often since we get a longer line from the last position to the current one. See problem #30.

**Comment by shiffman** [comment]
@meiamsome it's a feature, not a bug!  I'm not sure about this.  Anyone know what the original games does?  But this is all an experiment so fine either way!

**Comment by LeastCreative** [comment]
I just played the original 1979 asteroids on an emulator for a minute or two, and I can confirm that the lasers do in fact go faster if you shoot them while moving forward!

Take that with a grain of salt though, because we are already doing a few things wrong if emulating the original is the goal here (which I am assuming its not). Regardless, the original does in fact implement this feature

**Comment by LeastCreative** [comment]
list of things i noticed about the original game (if anyone is curious):

The bullets DO wrap!
The hud is off to the left for player 1 and to the right for player 2
Obviously the sounds are quite a bit different
The asteroids actually don't seem to be generated; there is only about 3 or 4 shapes for each size
The ship looks like a capital A instead of a triangle
The ships boost animation is a triangle instead of a... wiggly thing :P
The player is able to warp to a random location by pressing down (backwards) which may kill it
The game eventually spawns flying saucers that shoot in your general direction**
The game only allows 4 bullets to exist at any given time**

I will not add these things as separate issues because frankly our version is cooler, just thought I would mention it

**these ones seem like a good idea to actually implement
