### ISSUE TITLE
Do we have a Slack/Discord/Something else?

### ISSUE THREAD

**Issue by MunWolf** [CodingTrain/Asteroids#31]
Title says it all, do we have something like this atm?

**Comment by meiamsome** [comment]
There is a slack available for Dan's patrons:

https://www.patreon.com/codingrainbow/posts

Whether or not we should have something else for collaborators, I guess we should ask @shiffman

**Comment by MunWolf** [comment]
Ok, I am just finishing my university so got no money for the patreon xD
Well we shall see.

**Comment by NetStorm84** [comment]
I have just made a Slack team so that we can discuss more coding options

**Comment by NetStorm84** [comment]
https://communityasteroids.slack.com/shared_invite/MTE4MDI4ODAzMDQ0LTE0ODE5MTU2NDMtZjc3MGIzM2M4ZA

**Comment by shiffman** [comment]
I am not opposed to making the patron slack channel open to contributors to the channel in other ways besides patron donations.  Because the audience for the channel has grown easily, it's nice to have a small core community to discuss topics and ideas.  But I'm happy to think about ways that the barrier doesn't have to be financial.  All this said, having a slack channel for this asteroids game sounds like a great idea!  I'll join in if that's ok.

**Comment by ada-lovecraft** [comment]
I think it'd be a better idea to open the organization up for access from gitter.

If you aren't familiar with gitter, it's a GitHub related chat service where we can create public chatrooms for public repos. This way, we can discuss, on a per repo basis, things like... this, or #29

**Comment by shiffman** [comment]
Gitter is enabled now!

**Comment by ada-lovecraft** [comment]
[![Join the chat at https://gitter.im/CodingRainbow/Asteroids](https://badges.gitter.im/CodingRainbow/Asteroids.svg)](https://gitter.im/CodingRainbow/Asteroids?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
